packages: []

catalogs:
  dev:
    tsdown: ^0.21.1
  prod:
    '@clack/core': ^1.1.0
    '@clack/prompts': ^1.1.0
    ansis: ^4.2.0
    cac: ^7.0.0
    fast-npm-meta: ^1.4.2
    yaml: ^2.7.0
allowBuilds:
  esbuild: false

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
